services:
  db:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: matan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydata
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5332:5432"
    networks:
      - app-network
    restart: unless-stopped

  app:
    build: .
    container_name: game-exchange-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydata
      - SPRING_DATASOURCE_USERNAME=matan
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: