### GET request to example server
GET http://localhost:8080

###

### GET request to example server
GET http://localhost:8080/api/v1/posts/2

###
###
PATCH http://localhost:8080/api/v1/posts/4
Content-Type: application/json

{
  "price": -2,
  "status": "fasfd"
}
###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "productName" : "Ghost",
  "price" : 5,
  "picUrl" : "https://example.com",
  "userId" : 1,
  "description": "Brand new"
}
###
GET localhost:8080/actuator/metrics/http.server.requests

