spring.application.name=game-exchange
spring.datasource.url=jdbc:postgresql://localhost:5332/mydata
spring.datasource.username=matan
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true


management.endpoint.health.show-details=always
management.endpoint.env.show-values=always
management.endpoints.web.exposure.include=health,env,beans,conditions,mappings,loggers,metrics