spring.application.name=game-exchange

# Trust Railway's reverse-proxy headers so redirect URIs use https://
server.forward-headers-strategy=framework
spring.datasource.url=jdbc:postgresql://gondola.proxy.rlwy.net:29942/railway
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create


FRONTEND_URL=https://matanmoalemm.vercel.app

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
spring.security.oauth2.client.provider.google.user-name-attribute=sub


app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=86400000

## All Spring internals
#logging.level.org.springframework=DEBUG
#
## Your specific package
#logging.level.com.yourpackage=DEBUG
#
## SQL queries
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE